### ISSUE TITLE
Possible mention to autoimport in documentation

### ISSUE THREAD

**Issue by lyz-code** [Tiendil/smart-imports#17]
Hey @Tiendil , I'm the developer of [autoimport](https://lyz-code.github.io/autoimport/) which tackles the same problem as smart-imports with a different approach.

I've [added a note in our docs](https://github.com/lyz-code/autoimport/pull/81) featuring your tool in case any user reading them find your approach more appealing. 

Would you like to feature autoimport back in your docs? if you do, I can make a PR

**Comment by Tiendil** [comment]
Hi!

>Would you like to feature autoimport back in your docs? if you do, I can make a PR

Good idea. More tools — better :-)

I added the "Similar projects" section to README: https://github.com/Tiendil/smart-imports#similar-projects with a short description of autoimport.

Make PR if you want to add some words to the description or if you know any similar projects.

**Comment by lyz-code** [comment]
Thanks ^^!
